alias empress='ssh shell013@empress.csusm.edu'
alias esftp='sftp shell013@empress.csusm.edu'
alias hw='cd ~/programming/cpp/'
alias gt='cd ~/pCloudDrive/GT/'
alias modvim='vim ~/.vimrc'
alias Mod='vim ~/.bash_aliases && source ~/.bashrc && echo "complete"'
alias projects='cd ~/projects/'
alias repos='cd ~/repos/'
alias up2date='sudo apt update && sudo apt upgrade && echo "Upgrade Complete"'
alias gitdir='cd ~/git_repo'

